const COURSE_SCREEN = 'COURSE_SCREEN';
const SELECT_COURSE_SCREENT = 'SELECT_COURSE_SCREENT';
const LOGIN_SCREEN = 'LOGIN_SCREEN';
const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
const FLASH_SCREEN = 'FLASH_SCREEN';
const SECTION_SCREEN = 'SECTION_SCREEN';

export {
  COURSE_SCREEN,
  SELECT_COURSE_SCREENT,
  SECTION_SCREEN,
  LOGIN_SCREEN,
  SELECT_LANGUAGE,
  FLASH_SCREEN,
};
