const COURSE_SCREEN = 'COURSE_SCREEN';
const LIST_COURSE_SCREEN = 'LIST_COURSE_SCREEN';
const LOGIN_SCREEN = 'LOGIN_SCREEN';
const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
const FLASH_SCREEN = 'FLASH_SCREEN';
const UNIT_SCREEN = 'UNIT_SCREEN';
const TEST_SCREEN = 'TEST_SCREEN';
const WORD_DETAIL_SCREEN = 'WORD_DETAIL_SCREEN';
const SETTING_SCREEN = 'SETTING_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';
const MY_COURSE_SCREEN = 'MY_COURSE_SCREEN';
const CHOOSE_WORD_TEST_SCREEN = 'CHOOSE_WORD_TEST_SCREEN'

export {
  COURSE_SCREEN,
  LIST_COURSE_SCREEN,
  MY_COURSE_SCREEN,
  UNIT_SCREEN,
  LOGIN_SCREEN,
  SELECT_LANGUAGE,
  FLASH_SCREEN,
  TEST_SCREEN,
  WORD_DETAIL_SCREEN,
  PROFILE_SCREEN,
  SETTING_SCREEN,
  CHOOSE_WORD_TEST_SCREEN,
};
